
FL_exclusive_resnet18_on_cifar10_with_50_users_split_point_[1, 2, 3]_epochs_500_seed_123
[Epoch : 1][User 34 with split point 2] [Loss  2.149 | Acc 37.930]
[Epoch : 1][User 37 with split point 2] [Loss  2.076 | Acc 41.855]
[Epoch : 1][User 39 with split point 2] [Loss  2.091 | Acc 39.062]
[Epoch : 1][User 45 with split point 2] [Loss  2.157 | Acc 39.238]
[Epoch : 1][User 32 with split point 2] [Loss  2.147 | Acc 35.312]
Traceback (most recent call last):
  File "/home/gyoon814/anaconda3/envs/SFL/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gyoon814/anaconda3/envs/SFL/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gyoon814/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/gyoon814/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/gyoon814/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/gyoon814/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/gyoon814/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/gyoon814/.vscode-server/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/gyoon814/research/baseline/main_exclusive.py", line 80, in <module>
  File "/home/gyoon814/research/baseline/train/avg.py", line 6, in HeteroAvg
    w_glob = copy.deepcopy(w[0][0])
KeyError: 0